# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # daily check at 01:00 AM
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint app/**/*.py

    - name: Test with pytest
      run: |
        pip install pytest-cov
        pytest --cov-report=xml --cov=app  -v

    - name: upload coverage
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}